(lambda (initial-state unknown)
  (letrec ((nth (lambda (n lst) (if (= n 0) (car lst) (nth (- n 1) (cdr lst)))))
           (step (lambda (ai-state world-state)
                   (let ((call-with-world (lambda (map lman ghosts fruits)
                                            (let ((at-coords (lambda (x y) (nth x (nth y map))))
                                                  (lman-env (lambda (up rg dn lf)
                                                              (cons 0
                                                                    (if (= lf 0)
                                                                        (if (= up 0)
                                                                            (if (= rg 0)
                                                                                (if (= dn 0)
                                                                                    3
                                                                                    2)
                                                                                1)
                                                                            0)
                                                                        3)))))
                                              (lman-env (at-coords (car lman) (- (cdr lman) 1))
                                                        (at-coords (+ (car lman) 1) (cdr lman))
                                                        (at-coords (car lman) (+ (cdr lman) 1))
                                                        (at-coords (- (car lman) 1) (cdr lman)))))))
                     (call-with-world (car world-state)
                                      (cadr (cadr world-state))
                                      (cadr (cdr world-state))
                                      (cdr (cdr (cdr world-state))))))))
    (let ((init (lambda (initial-state unknown)
                  (cons 0 step))))
      (init initial-state unknown))))
