
(in-package :ai)

(defun draw-map (map &optional custom-writer)
  (iter (with (width . height) = (map-size map))
        (for y from 0 below height)
        (iter (for x from 0 below width)
              (for user-obj = (when custom-writer (funcall custom-writer x y)))
              (for obj = (or user-obj
                             (ecase (map-cell (cons x y) map)
                                 (0 #\#)
                                 (1 #\Space)
                                 (2 #\.)
                                 (3 #\o)
                                 (4 #\%)
                                 (5 #\\)
                                 (6 #\=))))
              (format t "~c" obj))
        (format t "~%")))

(defun run-simulator (initial-world-state &key (max-turns 10000))
  (declare (optimize (debug 3)))
  (let ((game (gcc-init initial-world-state nil)))
    (iter (with ai-state = (car game))
          (with step = (cdr game))
          (for counter from 0 below max-turns)
          (for (new-ai-state . direction) = (funcall step ai-state initial-world-state))
          (setf ai-state new-ai-state))))
